### ISSUE TITLE
代码所需环境请教：fastNLP版本问题

### ISSUE THREAD

**Issue by Lucia517** [daiyongya/markbert#3]
1.我首先安装的是FastNLP1.0.1版本，运行代码是会出现
`Traceback (most recent call last):
  File "run_ner.py", line 6, in <module>
    from fastNLP.modules import ConditionalRandomField
ImportError: cannot import name 'ConditionalRandomField' from 'fastNLP.modules' (/root/miniconda3/envs/constdecoder/lib/python3.8/site-packages/fastNLP/modules/__init__.py)
Traceback (most recent call last):
  File "run_ner.py", line 6, in <module>
    from fastNLP.modules import ConditionalRandomField
ImportError: cannot import name 'ConditionalRandomField' from 'fastNLP.modules' (/root/miniconda3/envs/constdecoder/lib/python3.8/site-packages/fastNLP/modules/__init__.py)`错误
2.当我把版本降低到FastNLP0.4.1版，又会出现如下错误：
`Traceback (most recent call last):
  File "run_ner.py", line 10, in <module>
    from load_data import load_ontonotes_cn
  File "/root/markbert/fastnlp-ner/load_data.py", line 1, in <module>
    from fastNLP.io.pipe import Conll2003NERPipe, OntoNotesNERPipe
ModuleNotFoundError: No module named 'fastNLP.io.pipe'
Traceback (most recent call last):
  File "run_ner.py", line 10, in <module>
    from load_data import load_ontonotes_cn
  File "/root/markbert/fastnlp-ner/load_data.py", line 1, in <module>
    from fastNLP.io.pipe import Conll2003NERPipe, OntoNotesNERPipe
ModuleNotFoundError: No module named 'fastNLP.io.pipe'`
所以想问一下您使用的FastNLP版本是什么？
可以的话可以提供一下requirements吗？麻烦了

**Comment by Lucia517** [comment]
不好意思，刚刚查询到，FastNLP的版本是 0.5.0
